"""tables

Revision ID: 08b9f084099c
Revises: 
Create Date: 2020-12-26 15:49:55.691173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b9f084099c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_name', sa.String(length=64), nullable=True),
    sa.Column('problem_link', sa.String(length=64), nullable=True),
    sa.Column('keywords', sa.String(length=140), nullable=True),
    sa.Column('tags', sa.String(length=140), nullable=True),
    sa.Column('platform', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_keywords'), 'problem', ['keywords'], unique=False)
    op.create_index(op.f('ix_problem_platform'), 'problem', ['platform'], unique=False)
    op.create_index(op.f('ix_problem_problem_link'), 'problem', ['problem_link'], unique=True)
    op.create_index(op.f('ix_problem_problem_name'), 'problem', ['problem_name'], unique=False)
    op.create_index(op.f('ix_problem_tags'), 'problem', ['tags'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('marked',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marked')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_problem_tags'), table_name='problem')
    op.drop_index(op.f('ix_problem_problem_name'), table_name='problem')
    op.drop_index(op.f('ix_problem_problem_link'), table_name='problem')
    op.drop_index(op.f('ix_problem_platform'), table_name='problem')
    op.drop_index(op.f('ix_problem_keywords'), table_name='problem')
    op.drop_table('problem')
    # ### end Alembic commands ###
